connection:
  username: root
  password: password1
spring:
  datasource:
    url: nulconnection:
              username: root
              password: password1
            spring:
              datasource:
                        spring:
                          datasource:
                            url: nulconnection:
                                      username: root
                                      password: password1
                                    spring:
                                      datasource:
                                        url: nulconnection:
                                                  username: root
                                                  password: password1
                                                spring:
                                                  datasource:
                                                    url: nul